[package]
name         = "mango_optimizer_js"
version      = "1.0.0-alpha.35"
edition      = "2021"
rust-version = "1.82"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
strip         = "symbols"

[dependencies]
serde                 = { version = "1.0.215" }
swc_common            = { version = "4.0.1", features = ["concurrent"] }
swc_core              = { version = "6.0.2", features = ["ecma_plugin_transform"] }
swc_ecma_ast          = { version = "4.0.1" }
swc_ecma_utils        = { version = "5.0.1" }
swc_ecma_visit        = { version = "4.0.1" }
swc_ecma_transforms   = { version = "6.0.0" }
swc_ecma_minifier     = { version = "5.0.1" }
swc_ecma_parser       = { version = "5.0.0" }
swc_plugin_macro      = { version = "1.0.0" }
swc_plugin_proxy      = { version = "4.0.0" }
swc_atoms             = { version = "2.0.0" }
swc_ecma_codegen      = { version = "4.0.2" }
swc_trace_macro       = { version = "2.0.0" }
testing               = { version = "4.0.0" }
tracing               = { version = "0.1.40", features = ["release_max_level_info"] }

[dev-dependencies]
swc_core = { features = ["testing_transform"], version = "6.0.2" }
testing  = { version = "4.0.0" }
