blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/GeeekyBoy/mango/discussions/categories/ideas
    about: Have an idea for a new feature? Let us know!
  - name: 📘 Documentation
    url: https://mangojs.geeekyboy.com/docs
    about: Make sure you've read the documentation before filing a bug report or proposing a feature.
