export default {
  createState: "a",
  getState: "b",
  setState: "c",
  createStatefulArray: "d",
  updateStatefulArray: "e",
  createEffect: "f",
  destroyEffect: "g",
  createListView: "h",
  createDynamicView: "i",
  createElement: "j",
  createHeadElement: "k",
  appendPropsToElement: "l",
  createLazyComponent: "m",
}